services:
  backend:
    image: alcxmtr/quirknotes_backend:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  frontend:
    image: alcxmtr/quirknotes_frontend:latest
    ports:
      - "3000:80"
    environment:
      - ENV=Docker
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
